//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_64140855.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartItem
    {
        public int CartItemId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> GameId { get; set; }
        public int Quantity { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual User User { get; set; }
    }
}
